<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.apple.preference.security</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>dontAllowPasswordResetUI</key>
								<true/>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.ManagedClient.preferences.8DED2626-A683-4849-A41D-39C774A4C630</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>8DED2626-A683-4849-A41D-39C774A4C630</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.okta.mobile</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>OktaVerify.OrgUrl</key>
								<string>https://${okta_short_url}</string>
								<key>OktaVerify.UserPrincipalName</key>
								<string>$USERNAME</string>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.ManagedClient.preferences.4C7D69F4-3544-4291-A163-DCC8CEC9E19B</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>4C7D69F4-3544-4291-A163-DCC8CEC9E19B</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.okta.mobile.auth-service-extension</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>OktaVerify.OrgUrl</key>
								<string>https://${okta_short_url}</string>
								<key>OktaVerify.PasswordSyncClientID</key>
								<string>${okta_psso_client}</string>
								<key>OktaVerify.UserPrincipalName</key>
								<string>$USERNAME</string>
								<key>PlatformSSO.ProtocolVersion</key>
								<string>2.0</string>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.ManagedClient.preferences.71C65EBB-85E5-424C-AFC8-0C4FF4C14DA6</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>71C65EBB-85E5-424C-AFC8-0C4FF4C14DA6</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string></string>
	<key>PayloadDisplayName</key>
	<string>Platform SSO - Okta Verify App Configuration</string>
	<key>PayloadEnabled</key>
	<true/>
	<key>PayloadIdentifier</key>
	<string>F0A83F4A-A3F1-42F3-9B8C-C7318EC710D5</string>
	<key>PayloadOrganization</key>
	<string>Project Mercury</string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>F0A83F4A-A3F1-42F3-9B8C-C7318EC710D5</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
