<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>Configuration</key>
			<array>
				<dict>
					<key>application_identifier</key>
					<string>B7F62B65BN.com.okta.mobile</string>
					<key>AssociatedDomains</key>
					<array>
						<string>authsrv:${okta_short_url}</string>
					</array>
				</dict>
				<dict>
					<key>application_identifier</key>
					<string>B7F62B65BN.com.okta.mobile.auth-service-extension</string>
					<key>AssociatedDomains</key>
					<array>
						<string>authsrv:${okta_short_url}</string>
					</array>
				</dict>
			</array>
			<key>PayloadDescription</key>
			<string>Only for 10.15 MacOS</string>
			<key>PayloadDisplayName</key>
			<string>ASSOCIATED_DOMAINS</string>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>B7F38B23-CDC8-4D19-89D8-B9A01DF67AC0</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.associated-domains</string>
			<key>PayloadUUID</key>
			<string>B7F38B23-CDC8-4D19-89D8-B9A01DF67AC0</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.okta.mobile.auth-service-extension</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>OktaVerify.EnrollmentOptions</key>
								<string>SilentEnrollmentEnabled</string>
								<key>OktaVerify.OrgUrl</key>
								<string>https://${okta_short_url}</string>
								<key>OktaVerify.PasswordSyncClientID</key>
								<string>${okta_psso_client}</string>
								<key>OktaVerify.UserPrincipalName</key>
								<string>$USERNAME</string>
								<key>PlatformSSO.ProtocolVersion</key>
								<string>2.0</string>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>3137E69F-8E58-40D4-94F6-327F3D4487C0</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>3137E69F-8E58-40D4-94F6-327F3D4487C0</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.okta.mobile</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>OktaVerify.EnrollmentOptions</key>
								<string>SilentEnrollmentEnabled</string>
								<key>OktaVerify.OrgUrl</key>
								<string>https://${okta_short_url}</string>
								<key>OktaVerify.UserPrincipalName</key>
								<string>$USERNAME</string>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>4851A290-8CA7-4C0B-9AE5-652DF64ACE00</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>4851A290-8CA7-4C0B-9AE5-652DF64ACE00</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.apple.preference.security</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>dontAllowPasswordResetUI</key>
								<true/>
							</dict>
						</dict>
					</array>
				</dict>
			</dict>
			<key>PayloadDisplayName</key>
			<string>Custom Settings</string>
			<key>PayloadIdentifier</key>
			<string>93A6EFEA-72C9-4CD7-9F73-C9D7B88C2219</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>93A6EFEA-72C9-4CD7-9F73-C9D7B88C2219</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>AuthenticationMethod</key>
			<string>Password</string>
			<key>ExtensionIdentifier</key>
			<string>com.okta.mobile.auth-service-extension</string>
			<key>Hosts</key>
			<array/>
			<key>PayloadDisplayName</key>
			<string>Single Sign-On Extensions Payload</string>
			<key>PayloadIdentifier</key>
			<string>730365BC-383C-47EC-BEAD-C8BC85741C59</string>
			<key>PayloadOrganization</key>
			<string>${okta_org_name}</string>
			<key>PayloadType</key>
			<string>com.apple.extensiblesso</string>
			<key>PayloadUUID</key>
			<string>730365BC-383C-47EC-BEAD-C8BC85741C59</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>PlatformSSO</key>
			<dict>
				<key>AccountDisplayName</key>
				<string>${okta_org_name} - IT</string>
				<key>AllowDeviceIdentifiersInAttestation</key>
				<true/>
				<key>AuthenticationMethod</key>
				<string>Password</string>
				<key>EnableAuthorization</key>
				<true/>
				<key>EnableCreateFirstUserDuringSetup</key>
				<true/>
				<key>EnableCreateUserAtLogin</key>
				<true/>
				<key>EnableRegistrationDuringSetup</key>
				<true/>
				<key>FileVaultPolicy</key>
				<array>
					<string>AttemptAuthentication</string>
				</array>
				<key>NewUserAuthenticationMethods</key>
				<array>
					<string>Password</string>
				</array>
				<key>NewUserAuthorizationMode</key>
				<string>Standard</string>
				<key>TokenToUserMapping</key>
				<dict>
					<key>AccountName</key>
					<string>macOSAccountUsername</string>
					<key>FullName</key>
					<string>macOSAccountFullName</string>
				</dict>
				<key>UseSharedDeviceKeys</key>
				<true/>
				<key>UserAuthorizationMode</key>
				<string>Standard</string>
			</dict>
			<key>TeamIdentifier</key>
			<string>B7F62B65BN</string>
			<key>Type</key>
			<string>Redirect</string>
			<key>URLs</key>
			<array>
				<string>https://${okta_short_url}/oauth2/v1/token</string>
				<string>https://${okta_short_url}/device-access/api/v1/nonce</string>
			</array>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string></string>
	<key>PayloadDisplayName</key>
	<string>${okta_org_name}</string>
	<key>PayloadEnabled</key>
	<true/>
	<key>PayloadIdentifier</key>
	<string>471D7AA5-6D37-44F8-9129-7349FB465000</string>
	<key>PayloadOrganization</key>
	<string>${okta_org_name}</string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>471D7AA5-6D37-44F8-9129-7349FB465000</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
